version: '3'
services:
  database:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'apitodo123'
    volumes:
      - ./../.db/data:/var/lib/mysql
